{
 "title": "Prom",
 "description": "Get started faster with Grafana Cloud then easily build these dashboards. https://grafana.com/products/cloud/\nOverview of metrics from Prometheus 2.0.  \nUseful for using prometheus to monitor your prometheus.\nRevisions welcome!",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "query_result(prometheus_tsdb_head_samples_appended_total)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "query_result(up{job=~\"$job\"})"
    }
   },
   {
    "name": "interval",
    "query": "1h, 3h, 6h, 12h, 1d, 2d, 7d, 30d, 90d, 180d"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Free space on the hard drive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{job=\"node\",instance=\"localhost:9100\",device!=\"/dev/sda2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hard Disk I/O (sec total)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_disk_io_time_seconds_total{device!=\"sr0\", device!=\"sda\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hard Disk I/O (read sec total)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "node_disk_read_time_seconds_total{device!=\"sda\", device!=\"sr0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hard Disk I/O (write sec total)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "node_disk_write_time_seconds_total{device!=\"sda\", device!=\"sr0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pressure I/O stalled (sec)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "node_pressure_io_stalled_seconds_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pressure I/O waiting (sec)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "node_pressure_io_waiting_seconds_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}