{
 "title": "TASK_09",
 "time": { "from": "now-1m", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU_USAGE_SCRIPT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "targets": [
    { "expr": "cpu_usage_script", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MEM_AVAIL_SCRIPT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "targets": [
    { "expr": "mem_avail_script", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DISK_AVAIL_SCRIPT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "targets": [
    { "expr": "disk_avail_script", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MEM_TOTAL_SCRIPT",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
   "targets": [
    { "expr": "mem_total_script", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MEM_FREE_SCRIPT",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 8 },
   "targets": [
    { "expr": "mem_free_script", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DISK_SIZE_SCRIPT",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 8 },
   "targets": [
    { "expr": "disk_size_script", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DISK_USED_SCRIPT",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 8 },
   "targets": [
    { "expr": "disk_used_script", "legendFormat": "__auto" }
   ]
  }
 ]
}